// builds index3.html = the built app with the Supabase client replaced by an in-memory mock (tables, storage, rpc, auth, functions)
import fs from 'fs'; import path from 'path'; import { ROOT } from './env.mjs';
let html = fs.readFileSync(path.join(ROOT, 'index.html'),'utf8');
const mock = `<script>
window.supabase = { createClient(){
  const now = Date.now();
  const tables = {profiles:[], instructions:[], runs:[], workspaces:[], views:[], instr_stats:[], feedback:[]};
  const session = {user:{id:'u1', email:'bjoern@ar-giri.com'}, access_token:'tok'};
  tables.profiles.push({id:'u1', email:'bjoern@ar-giri.com', name:'Björn', role:'admin', ws:'ar-giri.com', is_admin:true, created_at:new Date(now-8e7).toISOString()});
  tables.profiles.push({id:'u2', email:'anna@ar-giri.com', name:'Anna', role:'viewer', ws:'ar-giri.com', is_admin:false, created_at:new Date(now-4e7).toISOString()});
  tables.workspaces.push({ws:'ar-giri.com', brand:{name:'AR-Experts', color:'#004EAD', theme:'dark'}, folders:[{id:'f1', name:'Linie 3', teams:['t1']},{id:'f2', name:'Vorrichtungen', teams:[]}], teams:[{id:'t1', name:'Montage', members:[{email:'anna@ar-giri.com', role:'viewer'}]}], invites:[{email:'max@ar-giri.com', role:'creator'}]});
  window.__tables = tables;
  const q = (tbl) => { const st = {filters:[], order:null, single:false, count:false, head:false, op:'select', payload:null};
    const api = { select(cols, opts){ window.__sel = (window.__sel||[]).concat([tbl+':'+(cols||'*')]); if(opts&&opts.count){st.count=true; st.head=!!opts.head;} return api; }, eq(k,v){ st.filters.push([k,v]); return api; }, is(k,v){ st.filters.push([k,v,'is']); return api; }, in(k,arr){ st.filters.push([k,arr,'in']); return api; }, not(k,op,v){ st.filters.push([k,v,'not-'+op]); return api; }, gte(){ return api; }, order(){ return api; }, limit(){ return api; }, range(a,b){ st.range=[a,b]; return api; }, maybeSingle(){ st.single=true; return api; },
      insert(p){ st.op='insert'; st.payload=p; return api; }, upsert(p){ st.op='upsert'; st.payload=p; return api; }, update(p){ st.op='update'; st.payload=p; return api; }, delete(){ st.op='delete'; return api; },
      then(res, rej){ if(window.__mockOffline) return Promise.resolve({data:null, error:{message:'TypeError: Failed to fetch'}, count:null}).then(res, rej); if(window.__mockRefuse && tbl==='instructions' && st.op!=='select') return Promise.resolve({data:null, error:{code:'42501', message:'editing needs the editor role'}, count:null}).then(res, rej); /* v12.45: the database says no */ if(tbl==='instructions' && st.op==='select' && localStorage.getItem('gg_nosess')) return Promise.resolve(st.count ? {data:null, count:0, error:null} : {data: st.single ? null : [], error:null}).then(res, rej); /* v0.33: no anonymous table reads */ let rows = tables[tbl].filter(r => st.filters.every(([k,v,op]) => op==='is' ? (r[k]==null ? v==null : r[k]===v) : op==='in' ? v.includes(r[k]) : op==='not-is' ? !(r[k]==null ? v==null : r[k]===v) : r[k]===v));
        if(st.op==='insert'){ const arr = Array.isArray(st.payload)?st.payload:[st.payload]; tables[tbl].push(...arr); rows = arr; }
        if(st.op==='upsert'){ const key = tbl==='workspaces' ? 'ws' : 'id'; const i = tables[tbl].findIndex(r=>r[key]===st.payload[key]); if(i>=0) Object.assign(tables[tbl][i], st.payload); else tables[tbl].push(st.payload); rows=[st.payload]; }
        if(st.op==='update'){ rows.forEach(r=>Object.assign(r, st.payload)); }
        if(st.op==='delete'){ tables[tbl] = tables[tbl].filter(r=>!rows.includes(r)); }
        if(st.range && st.op==='select') rows = rows.slice(st.range[0], st.range[1]+1);
        const out = st.count ? {data:null, count:rows.length, error:null} : {data: st.single ? (rows[0]||null) : rows, error:null};
        return Promise.resolve(out).then(res, rej); } };
    return api; };
  // ---- GIRI Classic import fixtures (v0.32): a tiny old server with 2 projects and 3 instructions ----
  const F = p => location.origin + '/tests/' + p;
  const httpErr = code => ({data:null, error:{message:'Edge Function returned a non-2xx status code', context:{json: async () => ({error:code})}}});
  const OLD = {
    projects:[{id:'p1', name:'Linie 3', description:'', count:1, published:1, using_ar:false},{id:'p2', name:'Verpackung', description:'', count:1, published:0, using_ar:false}],
    teams:[{id:'t9', name:'Montage', members:3, count:1}],
    instructions:[
      {id:'A', name:'Spannvorrichtung rüsten', description:'Alte Beschreibung', project_id:'p1', project_name:'Linie 3', team_id:'t9', version:3, version_group_id:'A', creator:'Klaus Meier', published:true, released:true, locked:false, qr_code:null, created_at:'2024-03-01T10:00:00Z', updated_at:'2025-01-05T09:00:00Z', approvals:{technical:{at:'2024-12-01T08:00:00Z', user:{first_name:'Klaus', last_name:'Meier', email:'k@x.de'}}, privacy:{at:'2024-12-02T08:00:00Z', user:{email:'d@x.de'}}}},
      {id:'B', name:'Karton falten', description:'', project_id:'p2', project_name:'Verpackung', team_id:null, version:1, published:false, released:false, locked:false, qr_code:null, created_at:'2025-02-01T10:00:00Z', updated_at:'2025-02-01T10:00:00Z', approvals:null},
      {id:'C', name:'Großes Video', description:'', project_id:null, project_name:null, team_id:null, version:2, version_group_id:'C1', published:true, released:true, locked:false, qr_code:null, created_at:'2025-03-01T10:00:00Z', updated_at:'2025-03-01T10:00:00Z', approvals:{}},
      {id:'C1', name:'Großes Video', description:'', project_id:null, project_name:null, team_id:null, version:1, version_group_id:'C1', published:false, released:false, locked:false, qr_code:null, created_at:'2025-02-20T10:00:00Z', updated_at:'2025-02-20T10:00:00Z', approvals:{}, creator:'Maria Alt'} ] };
  const med = (id, url, type, bytes, pos, slot, slug) => ({id, url, type, width: type==='video' ? 640 : 800, height: type==='video' ? 480 : 600, quality:null, tags: slot!=null ? [...(slug ? ['pattern:pattern_1'] : []), 'pattern-slot:'+(slug||'media'), 'pattern-slot-index:'+slot] : [], bytes, position:pos, preview:null});
  const PAT_VN = {id:'pattern_1', name:'Vorher - Nachher', labels:{de:'Vorher - Nachher', en:'Before - After'}, default_language:'de', label_visible:true};
  const PAT_TZ = {id:'pattern_2', name:'Tageszeiten', labels:{de:'Tageszeiten'}, default_language:'de', label_visible:true};
  const PAT_CAP = {id:'pattern_3', name:'Without template', labels:{de:'Kein Template', en:'Without template'}, default_language:'en', label_visible:true};
  const PAT_NUM = {id:'pattern_4', name:'1 - 2 - 3 - 4', labels:{de:'1 - 2 - 3 - 4', en:'1 - 2 - 3 - 4'}, default_language:'de', label_visible:true};
  const DETAIL = {
    A:{id:'A', name:'Spannvorrichtung rüsten', description:'Alte Beschreibung', version:3, published:true, released:true, approvals:OLD.instructions[0].approvals, project_id:'p1', team_id:'t9', created_at:'2024-03-01T10:00:00Z', updated_at:'2025-01-05T09:00:00Z', qr_code:null,
      chapters:[
        {id:'c1', name:'Vorbereitung', description:'', position:1, steps:[
          {id:'s1', name:'Box öffnen', description:'Deckel nach oben klappen', position:1, hidden:false, chapter_id:'c1', icons:[{id:'i1', url:F('sym_wrench.png'), filename:'wrench.png'}], media:[med('m1', F('imp1.jpg'), 'image', 50000, 0, 0)], objects3d:0},
          {id:'s2', name:'Schraube lösen', description:'', position:2, hidden:false, chapter_id:'c1', icons:[], media:[med('m2a', F('test.webm'), 'video', 100000, 0, 0), med('m2b', F('test.webm?q=hd'), 'video', 102544, 1, 0)], objects3d:0} ]},
        {id:'c2', name:'Montage', description:'', position:2, steps:[
          {id:'s3', name:'Teil einsetzen', description:'Nur Text – kein Bild', position:1, hidden:false, chapter_id:'c2', icons:[], media:[], objects3d:1},
          {id:'s4', name:'Versteckt', description:'', position:2, hidden:true, chapter_id:'c2', icons:[], media:[med('m4', F('imp2.jpg'), 'image', 1, 0, 0)], objects3d:0},
          {id:'s5', name:'Schraube anziehen', description:'10 Nm', position:3, hidden:false, chapter_id:'c2', icons:[{id:'i1', url:F('sym_wrench.png'), filename:'wrench.png'}], pattern:PAT_VN, media:[med('m5b', F('imp2.jpg'), 'image', 2, 0, 1, 'nachher'), med('m5a', F('imp1.jpg'), 'image', 2, 1, 0, 'vorher')], objects3d:0} ]} ],
      steps:[{id:'s0', name:'Übersicht', description:'Loser Schritt vor den Kapiteln', position:0, hidden:false, chapter_id:null, icons:[], media:[med('m0', F('imp2.jpg'), 'image', 40000, 0, 0)], objects3d:0}] },
    B:{id:'B', name:'Karton falten', description:'', version:1, published:false, released:false, approvals:null, project_id:'p2', team_id:null, created_at:'2025-02-01T10:00:00Z', updated_at:'2025-02-01T10:00:00Z', qr_code:null, chapters:[],
      steps:[{id:'b1', name:'Karton nehmen', description:'', position:0, hidden:false, chapter_id:null, icons:[], media:[med('mb1', F('imp1.jpg'), 'image', 1, 0, 0)], objects3d:0},{id:'b2', name:'Falten', description:'', position:1, hidden:false, chapter_id:null, icons:[{id:'i1', url:F('sym_wrench.png'), filename:'wrench.png'}], media:[med('mb2', F('imp2.jpg'), 'image', 1, 0, 0)], objects3d:0},
        {id:'b3', name:'Kontrolle', description:'Dreimal täglich', position:2, hidden:false, chapter_id:null, icons:[], pattern:PAT_TZ, media:[med('mb3a', F('imp1.jpg'), 'image', 1, 0, 0, 'morgen'), med('mb3b', F('imp2.jpg'), 'image', 1, 1, 1, 'mittag'), med('mb3c', F('imp1.jpg'), 'image', 1, 2, 2, 'abend')], objects3d:0},
        {id:'b4', name:'Schraube', description:'<p>Das geht so schön auf.</p>', position:3, hidden:false, chapter_id:null, icons:[], pattern:PAT_CAP, media:[med('mb4', F('imp2.jpg'), 'image', 1, 0, 0, 'without-template')], objects3d:0},
        {id:'b5', name:'Kneten', description:'<ul><li><p>Basilikum</p></li><li><p>Olivenöl</p></li></ul><p></p>', position:4, hidden:false, chapter_id:null, icons:[], pattern:PAT_NUM, media:[med('mb5a', F('imp1.jpg'), 'image', 1, 0, 0, '1'), med('mb5c', F('imp2.jpg'), 'image', 1, 1, 2, '3')], objects3d:0},
        // v12.37.1: a "1 - 2 - 3 - 4" pattern where only slot 1 holds a file (the others are empty placeholder slots) → ONE step, no "(2)…(4)"; and a blank last step → dropped
        {id:'b6', name:'Formen', description:'', position:5, hidden:false, chapter_id:null, icons:[], pattern:PAT_NUM, media:[med('mb6a', F('imp1.jpg'), 'image', 1, 0, 0, '1'), med('mb6b', null, 'image', 0, 1, 1, '2'), med('mb6c', '', 'image', 0, 2, 2, '3'), med('mb6d', null, 'image', 0, 3, 3, '4')], objects3d:0},
        {id:'b7', name:'', description:'<p></p>', position:6, hidden:false, chapter_id:null, icons:[], media:[], objects3d:0}] },
    C:{id:'C', name:'Großes Video', description:'', version:2, published:true, released:true, approvals:{}, project_id:null, team_id:null, created_at:'2025-03-01T10:00:00Z', updated_at:'2025-03-01T10:00:00Z', qr_code:null, chapters:[],
      steps:[{id:'c1s', name:'Riesenvideo', description:'', position:0, hidden:false, chapter_id:null, icons:[], media:[med('mc1', F('big.webm'), 'video', 300*1024*1024, 0, 0)], objects3d:0},
        {id:'c2s', name:'Wackelig', description:'', position:1, hidden:false, chapter_id:null, icons:[], media:[med('mc2', F('imp1.jpg')+'?flaky=1', 'image', 50000, 0, 0)], objects3d:0},
        {id:'c3s', name:'Kaputt', description:'', position:2, hidden:false, chapter_id:null, icons:[], media:[med('mc3', F('imp2.jpg')+'?dead=1', 'image', 50000, 0, 0)], objects3d:0}] } };
  const giriImportMock = async body => {
    window.__imp = (window.__imp||[]).concat([{action:body.action, server:body.server, token:body.token, id:body.id, path:body.path, url:body.url}]);
    await new Promise(r => setTimeout(r, 60));
    if(!/^https:\\/\\//.test(body.server||'')) return httpErr('server_https');
    if(body.action==='connect'){ if(body.password!=='geheim') return httpErr('classic:INVALID_CREDENTIALS'); return {data:{token:'old-session-token', user:{email:body.email, name:'Björn Test', is_org_admin:true, is_super_admin:false}, organization:{id:'o1', name:'AR-Experts Classic'}}, error:null}; }
    if(body.token!=='old-session-token') return httpErr('classic:UNAUTHORIZED');
    if(body.action==='list') return {data:OLD, error:null};
    if(body.action==='structure') return {data:{users:[{id:'u1',email:'bjoern@ar-giri.com',name:'Björn S.',is_org_admin:true,status:'active'},{id:'u2',email:'anna@ar-giri.com',name:'Anna Alt',is_org_admin:false,status:'active'},{id:'u3',email:'max@ar-giri.com',name:'Max Neu',is_org_admin:false,status:'invited'},{id:'u4',email:'gast@extern.de',name:'Gast Extern',is_org_admin:false,status:'active'}],
      teams:[{id:'t9',name:'Montage',description:'',members:[{email:'anna@ar-giri.com',name:'Anna Alt',role:'editor'},{email:'max@ar-giri.com',name:'Max Neu',role:'viewer'},{email:'gast@extern.de',name:'Gast Extern',role:'viewer'}]},{id:'t10',name:'Qualität',description:'',members:[{email:'anna@ar-giri.com',name:'Anna Alt',role:'compliance_approver'}]}],
      projects:OLD.projects.map(p => ({id:p.id, name:p.name, description:''}))}, error:null};
    if(body.action==='instruction') return DETAIL[body.id] ? {data:{instruction:DETAIL[body.id]}, error:null} : httpErr('classic:NOT_FOUND');
    if(body.action==='copy'){ if(/big\\.webm/.test(body.url)) return httpErr('too_large'); if(/dead=1/.test(body.url)) return httpErr('classic:HTTP_504'); if(/flaky=1/.test(body.url)){ window.__flaky = (window.__flaky||0)+1; if(window.__flaky % 2 === 1) return httpErr('classic:HTTP_504'); } if(!/^ar-giri\\.com\\//.test(body.path)) return httpErr('path'); const ct = /\\.png/.test(body.url) ? 'image/png' : /\\.webm/.test(body.url) ? 'video/webm' : 'image/jpeg'; window.__copies = (window.__copies||[]).concat([body.path]); return {data:{path:body.path, url:body.url.replace(/\\?.*$/, ''), bytes:1234, contentType:ct}, error:null}; }
    return httpErr('action');
  };
  return {
    from: q,
    rpc: async (name, args) => { window.__rpc = (window.__rpc||[]).concat([{name, args}]); if(name==='open_instr'){ const row = tables.instructions.concat(tables.instructions_hidden||[]).find(r=>r.id===args.p_id && r.status==='published'); if(!row) return {data:null, error:null}; if(row.data && row.data.shareKey && args.p_key !== row.data.shareKey) return {data:{stale:true}, error:null}; const pw = window.__mockPw; if(pw && args.p_pw!==pw) return {data:{locked:true}, error:null}; return {data:{locked:false, row}, error:null}; } if(name==='gdpr_export_user'){ const me = tables.profiles[0]; if(!(me.is_admin || me.role==='admin')) return {data:null, error:{code:'42501', message:'admin only'}}; const p = tables.profiles.find(x => x.email===args.p_email) || null; return {data:{email:args.p_email, workspace:me.ws, exported_by:me.email, profile:p, team_memberships:[], invites:[], instructions_created_or_edited:tables.instructions.filter(i => p && i.data && i.data.createdBy===p.name).map(i => ({id:i.id, title:i.title})), feedback:[], runs:[], ai_usage:[]}, error:null}; } if(name==='gdpr_erase_user'){ const me = tables.profiles[0]; if(!(me.is_admin || me.role==='admin')) return {data:null, error:{code:'42501', message:'admin only'}}; if(args.p_email===me.email) return {data:null, error:{code:'42501', message:'you cannot erase your own account'}}; const k = tables.profiles.findIndex(x => x.email===args.p_email); const p = k>=0 ? tables.profiles.splice(k,1)[0] : null; let n=0; if(p) tables.instructions.forEach(i => { if(i.data && i.data.createdBy===p.name){ i.data.createdBy='Gelöschter Nutzer'; n++; } }); return {data:{email:args.p_email, profile_deleted:!!p, instructions_anonymised:n}, error:null}; } return {data:null, error:null}; },
    auth: { getSession: async()=>({data:{session: localStorage.getItem('gg_nosess') ? null : session}}), onAuthStateChange(cb){ setTimeout(()=>cb('SIGNED_IN', localStorage.getItem('gg_nosess') ? null : session), 50); }, getUser: async()=>({data:{user: localStorage.getItem('gg_nosess') ? null : session.user}}), signInWithOtp: async()=>({error:null}), signInWithOAuth: async(o)=>{ window.__oauth = o; return {error:null}; }, signOut: async()=>{} },
    storage: { from(){ return { upload: async(path)=>(window.__mockOffline ? {data:null, error:{message:'Failed to fetch'}} : {data:{path}, error:null}), remove: async()=>({}) }; } },
    functions: { invoke: async (name, {body}) => { if(name==='giri-import'){ return giriImportMock(body); } if(name==='pdf-analyze'){ window.__pdfCalls = (window.__pdfCalls||0)+1; window.__pdfBytes = body.pdf.length; if(window.__pdfErr) return {data:{error:window.__pdfErr}, error:null}; const r = await fetch('tests/pdf_ai_response.json'); await new Promise(x=>setTimeout(x,200)); return {data: await r.json(), error:null}; } window.__invoked = (window.__invoked||[]).concat([{target:body.target, instrId:body.instrId, ui:body.ui?body.ui.length:undefined}]); if(body.ui){ const map = {}; body.ui.forEach(x => map[x.k] = '['+body.target+'] '+x.v); await new Promise(r=>setTimeout(r,100)); return {data:{map}, error:null}; } if(body.texts){ const pre = body.target==='ZH' ? '夹具设置 ' : body.target==='PL' ? 'Zażółć gęślą jaźń ' : '['+body.target+'] '; return {data:{translations: body.texts.map(x => x ? pre + x : '')}, error:null}; } const row = tables.instructions.find(r=>r.id===body.instrId); const map = {}; if(row){ map.title = '[' + body.target + '] ' + row.title; for(const st of row.data.steps){ if(st.kind==='chapter') map['ch:'+st.id] = '['+body.target+'] '+st.title; else { map['t:'+st.id] = '['+body.target+'] '+st.title; map['d:'+st.id] = st.desc ? '['+body.target+'] '+st.desc : ''; map['w:'+st.id] = st.warn ? '['+body.target+'] '+st.warn : ''; } } } await new Promise(r=>setTimeout(r,150)); return {data:{map, cached:false}, error:null}; } },
    channel(){ const c = {on(){ return c; }, subscribe(){ return c; }}; return c; }, removeChannel(){}
  }; } };
</script>`;
html = html.replace(/<script src="https:\/\/cdn.jsdelivr.net[^>]*><\/script>/, mock);
html = html.replace(/https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/jspdf\/[^"]*/, 'tests/vendor/jspdf.umd.min.js').replace(/https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/qrcodejs\/[^"]*/, 'tests/vendor/qrcode.min.js');
fs.writeFileSync(path.join(ROOT, 'index3.html'), html);
console.log('index3 rebuilt');
